# Copyright (c) 2021 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0

manifest:
  self:
    west-commands: scripts/west-commands.yml

  defaults:
    remote: aesc-silicon
    revision: main

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: aesc-silicon
      url-base: https://github.com/aesc-silicon
    - name: spinalhdl
      url-base: https://github.com/spinalhdl

  projects:
    - name: elements-zephyr
      revision: v3.7.0-aesc
      import:
        path-allowlist: modules/elements/*
    - name: elements-zibal
      path: modules/elements/zibal
    - name: elements-nafarr
      path: modules/elements/nafarr
    - name: elements-vexriscv
      path: modules/elements/vexriscv
    - name: SpinalCrypto
      revision: master
      path: modules/elements/SpinalCrypto
      remote: spinalhdl
